import { useMemo, useState } from 'react';
import { PlayerBuild, CareerSettings, CareerSave, GameLog } from '../domain/models';
import { archetype, overall, similarities } from '../domain/derived';
import { createCareer } from '../domain/createCareer';
import { colleges } from '../data/colleges';
import { assignRole, simulateCollegeGame } from '../simulation/game';
import { persistSimulationStep, saveCareer } from '../persistence/db';
import './style.css';
const defaultPlayer: PlayerBuild={name:'Jordan Ellis',position:'SG',heightInches:77,weightPounds:205,hometown:'Akron, OH',playStyle:'Three-level scorer',personality:'Grinder',ratings:{shooting:78,finishing:74,playmaking:69,defense:71,rebounding:55,athleticism:76}};
const defaultSettings: CareerSettings={seed:'browser-hoops-1',autosaveFrequency:'afterEveryGame',difficulty:'balanced'};
export function App(){ const [player,setPlayer]=useState(defaultPlayer); const [settings,setSettings]=useState(defaultSettings); const [career,setCareer]=useState<CareerSave>(); const [logs,setLogs]=useState<GameLog[]>([]); const preview=useMemo(()=>createCareer(player,settings),[player,settings]); const role=career?assignRole(career):undefined; async function start(collegeId:string){ const c=createCareer(player,settings,collegeId); setCareer(c); await saveCareer(c); } async function sim(){ if(!career)return; const result=simulateCollegeGame(career); await persistSimulationStep(result.save,result.log); setCareer(result.save); setLogs([result.log,...logs]); }
return <main className="shell"><header><h1>Browser Hoops</h1><p>Solo basketball career simulator vertical slice.</p></header><section className="grid"><article className="card"><h2>1. Create Player</h2><label>Name <input value={player.name} onChange={e=>setPlayer({...player,name:e.target.value})}/></label><label>Position <select value={player.position} onChange={e=>setPlayer({...player,position:e.target.value as any})}>{['PG','SG','SF','PF','C'].map(p=><option key={p}>{p}</option>)}</select></label><div className="ratings">{Object.entries(player.ratings).map(([k,v])=><label key={k}>{k} <input type="range" min="25" max="99" value={v} onChange={e=>setPlayer({...player,ratings:{...player.ratings,[k]:Number(e.target.value)}})}/><b>{v}</b></label>)}</div><p><b>Overall:</b> {overall(player)} · <b>Archetype:</b> {archetype(player)}</p><p>{similarities(player).join(' · ')}</p></article><article className="card"><h2>2. Settings</h2><label>Seed <input value={settings.seed} onChange={e=>setSettings({...settings,seed:e.target.value})}/></label><p className="muted">Locked after creation: seed, difficulty. Editable later: autosave frequency.</p><h3>Recruiting Profile</h3><p>{preview.recruiting.summary}</p><p>Rank #{preview.recruiting.rank} · {preview.recruiting.stars}★ · confidence {preview.recruiting.scoutConfidence}%</p></article><article className="card wide"><h2>3. Choose from exactly four offers</h2><div className="offers">{preview.offers.map(o=>{const c=colleges.find(x=>x.id===o.collegeId)!; return <button key={o.collegeId} onClick={()=>start(o.collegeId)}><b>{c.name}</b><span>{o.promisedRole}, {o.minutes} min</span><small>Fit {o.fitScore}: {o.pitch}</small></button>})}</div></article>{career&&<article className="card wide"><h2>Career Home</h2><p>{career.player.name} at {colleges.find(c=>c.id===career.collegeId)?.name}</p><p>{role?.role} · {role?.minutes} min · trust {role?.coachTrust} · {role?.health}</p><button className="primary" onClick={sim}>Simulate next college game</button></article>}<article className="card wide"><h2>History & Game Logs</h2>{logs.length===0?<p>No games yet. Simulation persists snapshot, autosave, and log atomically.</p>:logs.map(l=><p key={l.id}>Game {l.gameNumber}: {l.result} {l.teamScore}-{l.opponentScore} vs {l.opponent}; {l.points}/{l.rebounds}/{l.assists}</p>)}{career?.history.map(h=><p key={h} className="muted">{h}</p>)}</article></section></main> }
