import { useEffect, useMemo, useRef, useState } from 'react';
import { PlayerBuild, CareerSettings, CareerSave, GameLog } from '../domain/models';
import { archetype, overall, similarities } from '../domain/derived';
import { createCareer } from '../domain/createCareer';
import { colleges } from '../data/colleges';
import { assignRole, simulateCollegeGame } from '../simulation/game';
import { listSaves, listTemplates, loadCareer, loadGameLogs, persistSimulationStep, saveCareer, saveTemplate } from '../persistence/db';
import './style.css';

type Screen = 'saves' | 'creator' | 'settings' | 'career';
type SimTarget = 'one game' | 'week' | 'month' | 'all-star break' | 'playoffs' | 'season';
const defaultPlayer: PlayerBuild={name:'Jordan Ellis',position:'SG',heightInches:77,weightPounds:205,hometown:'Akron, OH',playStyle:'Three-level scorer',personality:'Grinder',ratings:{shooting:78,finishing:74,playmaking:69,defense:71,rebounding:55,athleticism:76}};
const defaultSettings: CareerSettings={seed:'browser-hoops-1',autosaveFrequency:'afterEveryGame',difficulty:'balanced',godMode:false};
const simCounts: Record<SimTarget, number> = {'one game':1,week:3,month:10,'all-star break':18,playoffs:32,season:36};

export function App(){
  const [screen,setScreen]=useState<Screen>('saves');
  const [player,setPlayer]=useState(defaultPlayer);
  const [settings,setSettings]=useState(defaultSettings);
  const [career,setCareer]=useState<CareerSave>();
  const [logs,setLogs]=useState<GameLog[]>([]);
  const [saves,setSaves]=useState<{id:string;name:string;updatedAt:string}[]>([]);
  const [templates,setTemplates]=useState<{id:string;name:string;player:PlayerBuild}[]>([]);
  const [isSim,setIsSim]=useState(false);
  const pauseRef=useRef(false);
  const preview=useMemo(()=>createCareer(player,settings),[player,settings]);
  const role=career?assignRole(career):undefined;
  async function refresh(){ setSaves(await listSaves()); setTemplates(await listTemplates()); }
  useEffect(()=>{ refresh(); },[]);
  async function openSave(id:string){ const c=await loadCareer(id); if(!c)return; setCareer(c); setLogs(await loadGameLogs(id)); setScreen('career'); }
  async function start(collegeId:string){ const c=createCareer(player,settings,collegeId); await saveCareer(c); setCareer(c); setLogs([]); setScreen('career'); await refresh(); }
  async function template(){ await saveTemplate({id:crypto.randomUUID(),name:`${player.name} ${player.position}`,player,createdAt:new Date().toISOString()}); await refresh(); }
  async function sim(target:SimTarget){ if(!career||isSim)return; pauseRef.current=false; setIsSim(true); let next=career; for(let i=0;i<simCounts[target]&&!pauseRef.current;i++){ const result=simulateCollegeGame(next); await persistSimulationStep(result.save,result.log); next=result.save; setCareer(next); setLogs(l=>[result.log,...l]); await new Promise(r=>setTimeout(r,120)); } setIsSim(false); await refresh(); }
  const selectedCollege=career&&colleges.find(c=>c.id===career.collegeId);
  return <main className="appShell">
    {screen==='saves'&&<section className="landing"><div className="hero"><p className="eyebrow">Browser Hoops</p><h1>Career saves dashboard</h1><p>Manage long-form, Basketball GM-inspired solo careers. No on-court controls: build your player, choose training, make career decisions, and sim one game at a time.</p><button className="primary" onClick={()=>setScreen('creator')}>Create a new career save</button></div><div className="panel"><h2>Your save files</h2>{saves.length===0?<p className="muted">No IndexedDB saves yet.</p>:saves.map(s=><button className="saveRow" key={s.id} onClick={()=>openSave(s.id)}><b>{s.name}</b><span>{new Date(s.updatedAt).toLocaleString()}</span></button>)}</div></section>}
    {screen==='creator'&&<section className="flow"><Top step="1" title="Create player or load template" back={()=>setScreen('saves')}/><div className="grid"><article className="card"><h2>Player builder</h2><label>Name <input value={player.name} onChange={e=>setPlayer({...player,name:e.target.value})}/></label><label>Position <select value={player.position} onChange={e=>setPlayer({...player,position:e.target.value as any})}>{['PG','SG','SF','PF','C'].map(p=><option key={p}>{p}</option>)}</select></label><label>Hometown <input value={player.hometown} onChange={e=>setPlayer({...player,hometown:e.target.value})}/></label><div className="ratings">{Object.entries(player.ratings).map(([k,v])=><label key={k}>{k}<input type="range" min="25" max="99" value={v} onChange={e=>setPlayer({...player,ratings:{...player.ratings,[k]:Number(e.target.value)}})}/><b>{v}</b></label>)}</div><p><b>{overall(player)} OVR</b> · {archetype(player)} · {similarities(player).join(' · ')}</p><button onClick={template}>Save as template</button><button className="primary" onClick={()=>setScreen('settings')}>Continue to settings</button></article><article className="card"><h2>Templates</h2>{templates.length===0?<p className="muted">Saved player templates appear here.</p>:templates.map(t=><button className="saveRow" key={t.id} onClick={()=>setPlayer(t.player)}><b>{t.name}</b><span>{overall(t.player)} OVR {archetype(t.player)}</span></button>)}</article></div></section>}
    {screen==='settings'&&<section className="flow"><Top step="2" title="Career settings, recruiting, and offers" back={()=>setScreen('creator')}/><div className="grid"><article className="card"><h2>Settings</h2><label>Seed <input value={settings.seed} onChange={e=>setSettings({...settings,seed:e.target.value})}/></label><label>Difficulty <select value={settings.difficulty} onChange={e=>setSettings({...settings,difficulty:e.target.value as any})}><option>balanced</option><option>forgiving</option><option>harsh</option></select></label><label className="toggle"><input type="checkbox" checked={settings.godMode} onChange={e=>setSettings({...settings,godMode:e.target.checked})}/> Enable God Mode editor</label><p className="muted">God Mode can edit ratings, position, college, draft info, injuries, goals, morale, and contracts. History, logs, awards, recruiting, transactions, role, minutes, and archetype stay protected.</p></article><article className="card"><h2>Recruiting profile</h2><p>{preview.recruiting.summary}</p><h3>#{preview.recruiting.rank} · {preview.recruiting.stars}★ · {preview.recruiting.projectedRole}</h3><p className="muted">Future data packs should include most D-I colleges with preseason ranking, prestige, scrutiny, and minutes-earning context.</p></article><article className="card wide"><h2>Choose one of four offers</h2><div className="offers">{preview.offers.map(o=>{const c=colleges.find(x=>x.id===o.collegeId)!;return <button key={o.collegeId} onClick={()=>start(o.collegeId)}><b>{c.name}</b><span>{o.promisedRole}, {o.minutes} min</span><small>{c.conference} · Prestige {c.prestige} · Fit {o.fitScore}</small></button>})}</div></article></div></section>}
    {screen==='career'&&career&&<section className="career"><aside><h2>{career.player.name}</h2><p>{selectedCollege?.name}</p>{['Home dashboard','Career history','Training focus','Decisions','God Mode','Overall saves leaderboard','End of season reviews'].map(x=><button key={x}>{x}</button>)}</aside><section className="workspace"><div className="simbar"><b>Sim</b>{(Object.keys(simCounts) as SimTarget[]).map(t=><button disabled={isSim} onClick={()=>sim(t)} key={t}>{t}</button>)}<button disabled={!isSim} onClick={()=>{pauseRef.current=true;setIsSim(false)}}>Pause</button></div><div className="grid"><article className="card"><h2>Home dashboard</h2><p><b>{overall(career.player)} OVR</b> · {archetype(career.player)} · {role?.role}</p><p>{role?.minutes} min · trust {role?.coachTrust} · morale {role?.morale} · {role?.health}</p><p className="muted">Request trades later, pick training focus, manage goals, and react to coach/team events.</p></article><article className="card"><h2>Training focus</h2>{Object.keys(career.player.ratings).map(k=><button className="pill" key={k}>{k}</button>)}</article><article className="card wide"><h2>History & game logs</h2>{logs.length===0?<p className="muted">No games yet. Every timeframe still persists one game at a time so simulation can pause between games.</p>:logs.map(l=><p key={l.id}>Game {l.gameNumber}: {l.result} {l.teamScore}-{l.opponentScore} vs {l.opponent}; {l.points}p/{l.rebounds}r/{l.assists}a</p>)}{career.history.slice(-5).map(h=><p key={h} className="muted">{h}</p>)}</article></div></section></section>}
  </main>;
}
function Top({step,title,back}:{step:string;title:string;back:()=>void}){return <header className="top"><button onClick={back}>← Back</button><p>Step {step}</p><h1>{title}</h1></header>}
